name: ci pipeline

on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'
    path:
      - '**.py'


jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: isort
      run: isort --check-only .
    - name: flake8
      run: flake8 .



